version: '3'
services:
  builder:
    build:
      context: build
      dockerfile: ./Dockerfile
    image: snake_builder:latest
    volumes:
      - ./artifacts:/snake/dist

  tester:
    build:
      context: tests
      dockerfile: ./Dockerfile
    image: snake_tester:latest
    depends_on:
      - builder
    volumes:
      - ./artifacts:/snake/dist

  deploy:
    build:
      context: deploy
      dockerfile: ./Dockerfile
    depends_on:
      - tester
      - builder
    volumes:
      - ./artifacts:/snake/dist
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=host.docker.internal:0



